// Basic types for the frontend
export interface Position {
    x: number;
    y: number;
}

export interface ArgumentNode {
    id: string; // Unique ID, can be generated by a library like nanoid
    type: 'argumentNode'; // Custom node type for React Flow
    position: { x: number; y: number }; // Position on the canvas
    data: {
        label: string; // The text content of the claim
        author: 'user' | 'llm';
    };
}

export interface ArgumentEdge {
    id: string;
    source: string; // ID of the source ArgumentNode
    target: string; // ID of the target ArgumentNode
    type: 'argumentEdge'; // Custom edge type
    data: {
        relation: 'supports' | 'refutes' | 'unpacks';
    };
    animated: boolean; // Makes the edge "flow"
}

export type Action = 'supports' | 'refutes' | 'unpacks'; 